REM INSERTING into TRACKING
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (31,'US',3,to_date('16-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (32,'JPN',3,to_date('18-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (33,'HK',3,to_date('21-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (14,'US',1,to_date('16-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (15,'US',1,to_date('16-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (34,'US',3,to_date('16-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (35,'JPN',3,to_date('18-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (36,'HK',3,to_date('21-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (5,'TW',2,to_date('16-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (6,'TW',2,to_date('16-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (7,'TW',2,to_date('16-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (8,'TW',2,to_date('16-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (9,'TW',2,to_date('16-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (10,'TW',2,to_date('16-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (11,'US',1,to_date('16-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (12,'US',1,to_date('16-11る-11','DD-MON-RR'));
Insert into TRACKING (TRACKING_ID,TRACK_STAT,ORDER_ID,INDATE) values (13,'US',1,to_date('16-11る-11','DD-MON-RR'));
