============CUSTOMERS================
create table CUSTOMERS(
CUST_ID		NUMBER(38) not null,
NAME		VARCHAR2(50),
EMAIL		VARCHAR2(50),
ADDRESS		VARCHAR2(50),
CITY		VARCHAR2(50),
COUNTRY		VARCHAR2(20),
CUST_PW		VARCHAR2(100)
);

CREATE SEQUENCE CUST_ID
	MINVALUE 1
	MAXVALUE 99999
	START WITH 1
	INCREMENT BY 1
	NOCACHE;
	
============ORDER_ITEMS================
create table ORDER_ITEMS(
ORDER_ID		NUMBER(38),
ISBN			NUMBER(38),
ITEM_PRICE	NUMBER(10,2),
QTY			NUMBER(38)	
);

============ORDERS================
create table ORDERS(
ORDER_ID		NUMBER(38),
AMOUNT			NUMBER(10,2),
INDATE			DATE,
ORDER_STAT		VARCHAR2(25),
SHIP_NAME		VARCHAR2(50),
SHIP_ADDRESS	VARCHAR2(50),
SHIP_CITY		VARCHAR2(50),
SHIP_COUNTRY	VARCHAR2(20),
CUST_ID			NUMBER(38),
TRACKING_ID		NUMBER(38)
);

CREATE SEQUENCE ORDER_ID
	MINVALUE 1
	MAXVALUE 99999
	START WITH 1
	INCREMENT BY 1
	NOCACHE;

============TRACKING================	
create table TRACKING(
TRACKING_ID	NUMBER(38),
TRACK_STAT	VARCHAR2(50),
ORDER_ID	NUMBER(38),
INDATE		DATE
);

CREATE SEQUENCE TRACKING_ID
	MINVALUE 1
	MAXVALUE 99999
	START WITH 1
	INCREMENT BY 1
	NOCACHE;
	
==========COMMENT_TABLE==================
create table COMMENT_TABLE(
COM_ID		NUMBER(38),
CUST_ID		NUMBER(38),
CONTENT		VARCHAR2(50),
ISBN		NUMBER(38)
);

CREATE SEQUENCE COM_ID
	MINVALUE 1
	MAXVALUE 99999
	START WITH 1
	INCREMENT BY 1
	NOCACHE;

==========BOOKS==================
create table BOOKS(
ISBN	NUMBER(38),
AUTHOR	VARCHAR2(500),
TITLE	VARCHAR2(500),
CAT_ID	NUMBER(38),
PRICE	NUMBER(10,2),
DESCR	VARCHAR2(1024),
DIST	VARCHAR2(10),
IMG		VARCHAR2(1024),
AVAB	VARCHAR2(25),
INDATE	DATE,
PUBDATE	DATE,
QTY	NUMBER(38)
);

CREATE SEQUENCE ISBN
	MINVALUE 1
	MAXVALUE 99999
	START WITH 1
	INCREMENT BY 1
	NOCACHE;

==========CATEGORIES==================
create table CATEGORIES(
CAT_ID		NUMBER(38),
CAT_NAME	VARCHAR2(50)
);

CREATE SEQUENCE CAT_ID
	MINVALUE 1
	MAXVALUE 99999
	START WITH 1
	INCREMENT BY 1
	NOCACHE;
	
==========ADMIN_TABLE==================
create table ADMIN_TABLE(
USERNAME	VARCHAR2(50),
PASSWORD	VARCHAR2(50)
);

	